### ISSUE TITLE
Some samples missing image files

### ISSUE THREAD

**Issue by sophia-long** [Orillusion/orillusion#310]
I attempted to run the samples by cloning the Orillusion GitHub repository. After building, some samples couldn't run properly, displaying the following errors:

```
Engine Version 0.6.9
 emscripten have loaded
:8000/PBR/Duck/Duck.gltf:1     Failed to load resource: the server responded with a status of 404 (Not Found)
VM362 LoaderBase.ts:67 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'onError')
VM13 Engine3D.ts:279 Engine Version 0.6.9
VM995 8534012f-34e3-44b3-a4ef-2d6fa892bc39:1 emscripten have loaded
:8000/gltfs/glb/lion.glb:1     Failed to load resource: the server responded with a status of 404 (Not Found)
VM362 LoaderBase.ts:27 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'onError')
    at VM362 LoaderBase.ts:27:29
VM1003 Engine3D.ts:279 Engine Version 0.6.9
VM1505 5ebd38b7-260a-4798-afe3-bcbd7132df2e:1 emscripten have loaded
VM1356 LoaderBase.ts:56     GET http://localhost:8000/PBR/Duck/Duck.gltf net::ERR_ABORTED 404 (Not Found)
(anonymous) @ VM1356 LoaderBase.ts:56
loadJson @ VM1356 LoaderBase.ts:55
(anonymous) @ VM1354 FileLoader.ts:36
load @ VM1354 FileLoader.ts:35
loadGltf @ VM1005 Res.ts:118
initScene @ VM997 Sample_PropertyAnimation.ts:28
run @ VM997 Sample_PropertyAnimation.ts:21
await in run (async)
(anonymous) @ VM997 Sample_PropertyAnimation.ts:67
VM1356 LoaderBase.ts:67 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'onError')
    at VM1356 LoaderBase.ts:67:29
(anonymous) @ VM1356 LoaderBase.ts:67
Promise.catch (async)
(anonymous) @ VM1356 LoaderBase.ts:66
loadJson @ VM1356 LoaderBase.ts:55
(anonymous) @ VM1354 FileLoader.ts:36
load @ VM1354 FileLoader.ts:35
loadGltf @ VM1005 Res.ts:118
initScene @ VM997 Sample_PropertyAnimation.ts:28
run @ VM997 Sample_PropertyAnimation.ts:21
await in run (async)
(anonymous) @ VM997 Sample_PropertyAnimation.ts:67
VM1512 Engine3D.ts:279 Engine Version 0.6.9
VM2014 b8b6d139-7218-44fc-8cba-4a5a2c4ff9ff:1 emscripten have loaded
VM1858 LoaderBase.ts:56     GET http://localhost:8000/gltfs/CesiumMan/CesiumMan_compress.gltf net::ERR_ABORTED 404 (Not Found)
```

It appears that the image files required by the samples are not included with the project. Could you please provide information on where to download these files in order to properly test the samples?

**Comment by lslzl3000** [comment]
We put all large assets in a standalone git repo https://github.com/Orillusion/assets

So for local dev, you can clone/init the submodule by
```bash
git submodule update --init
```

more details: https://github.com/Orillusion/orillusion/blob/main/.github/contributing.md#development-setup
