### ISSUE TITLE
[BUG]: 自定义canvas报错:  createBuffer failed, size is too large for the implementation when mappedAtCreation == true

### ISSUE THREAD

**Issue by unhana** [Orillusion/orillusion#335]
## Bug描述
简单明晰的描述问题所在
使用自定义canvas时， 报错：
Uncaught (in promise) DOMException: Device is lost
orillusion.es.js:1 Uncaught RangeError: Failed to execute 'createBuffer' on 'GPUDevice': createBuffer failed, size is too large for the implementation when mappedAtCreation == true
    at Yn.mapAsyncWrite (orillusion.es.js:1:48995)
    at Xn.writeBuffer (orillusion.es.js:4870:20018)
    at m.updateFrame (orillusion.es.js:6499:13466)
    at m.render (orillusion.es.js:6499:12365)
    at orillusion.es.js:6499:12129
## Bug复现流程
通过以下步骤产生bug:
1. 创建 '...'
2. 点击 '...'
3. 删除 '...'
4. 出现错误 '...'

## 期待的结果
简介明要的阐述你期待发生什么结果

## 报错截图
如果可以，提供发生错误的截图
<img width="1679" alt="image" src="https://github.com/Orillusion/orillusion/assets/30139056/7062d4d5-bb3c-4fad-8539-79eac61b24c6">

## 测试引擎版本:
本地运行出错的Orillusion引擎版本  "@orillusion/core": "^0.7.1",

## 本机系统 (请填写完整):
 - OS: mac
 - Browser: chrome 
 - Version: 119.0.6045.159（正式版本） (x86_64)

## 本机配置
- CPU:  2.2 GHz 六核Intel Core i7
- Graphics Card: 
- Radeon Pro 555X 4 GB
Intel UHD Graphics 630 1536 MB

## 代码示例
https://codepen.io/zhaoya-wang/pen/eYxyxvR

## 其他信息
添加关于bug的其他描述信息

**Comment by unhana** [comment]
通过debug源码找到问题了， canvas指定大小要通过style指定， 并且要带上单位， 比如px
<img width="585" alt="image" src="https://github.com/Orillusion/orillusion/assets/30139056/a04d12b4-b023-42be-a807-d071def964dc">
