### ISSUE TITLE
[BUG]: 开启后期效果BloomPost时，无法用pixel拾取

### ISSUE THREAD

**Issue by YBbread** [Orillusion/orillusion#350]
## Bug描述
开启后期效果BloomPost时，无法用pixel拾取

## Bug复现流程
通过以下步骤产生bug:
1. 创建 '开启pixel拾取模式，开启BloomPost后期效果'
2. 点击 '...'
3. 删除 '...'
4. 出现错误 'Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'get')
    at m.getRenderJob (orillusion.es.js:6499:13636)
    at Xo.activePost (orillusion.es.js:6499:8808)
    at Xo.addPost (orillusion.es.js:6499:9105)
    at Sample_SphereDraw.run (button.html:68:33)'

## 期待的结果
不知道算不算BUG

## 报错截图
![image](https://github.com/Orillusion/orillusion/assets/29371745/0d558998-6c9f-446b-8e96-68c89826c6a7)
![image](https://github.com/Orillusion/orillusion/assets/29371745/299e0b7c-ea3e-41e0-ac52-18fa01956cdd)
![image](https://github.com/Orillusion/orillusion/assets/29371745/9e329715-2965-45fb-ab43-5c30e3c899ea)

## 测试引擎版本:
本地运行出错的Orillusion引擎版本, e.g. 0.7.1

## 本机系统 (请填写完整):
谷歌浏览器
win10系统

**Comment by YBbread** [comment]
个人尝试可以用创建wordpanel的方式 解决
